version: '3'
services:

  postgres:
    image: postgres:latest
    ports:
      - 5858:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
    external: false
  redis_data: