version: '3'
services:

  postgres:
    image: postgres
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
    external: false
  redis_data: