version: '3'
services:

  master:
    image: "citusdata/citus:11.3.0"
    ports: ["5432:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      PGUSER: "docker"
      PGPASSWORD: "docker"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "mydatabase"
  worker:
    image: "citusdata/citus:11.3.0"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
    external: false
  redis_data:
  healthcheck-volume: